# Generated by Django 4.2.7 on 2026-02-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'Sedan'), ('HYBRID', 'Hybrid'), ('SPORTS', 'Sports')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horsepower', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('acceleration', models.DecimalField(decimal_places=2, help_text='0-100 km/h in seconds', max_digits=4)),
                ('description', models.TextField()),
                ('hero_image', models.ImageField(upload_to='cars/hero/')),
                ('video', models.FileField(blank=True, null=True, upload_to='cars/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('order', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cars.car')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
